// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dadachMovie;

namespace dadachMovie.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210113122708_MadeImdbIdInMoviesUnique")]
    partial class MadeImdbIdInMoviesUnique
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("Value")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("dadachMovie.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name_FA")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Nationality")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Nationality_FA")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Afghanistan",
                            Nationality = "Afghan"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Albania",
                            Nationality = "Albanian"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Algeria",
                            Nationality = "Algerian"
                        },
                        new
                        {
                            Id = 4,
                            Name = "American Samoa",
                            Nationality = "American Samoan"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Andorra",
                            Nationality = "Andorran"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Angola",
                            Nationality = "Angolan"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Anguilla",
                            Nationality = "Anguillian"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Antarctica",
                            Nationality = "?"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Antigua and Barbuda",
                            Nationality = "Antiguan, Barbudan"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Argentina",
                            Nationality = "Argentinean"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Armenia",
                            Nationality = "Armenian"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Aruba",
                            Nationality = "Aruban"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Australia",
                            Nationality = "Australian"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Austria",
                            Nationality = "Austrian"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Azerbaijan",
                            Nationality = "Azerbaijani"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Bahamas",
                            Nationality = "Bahamian"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Bahrain",
                            Nationality = "Bahraini"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Bangladesh",
                            Nationality = "Bangladeshi"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Barbados",
                            Nationality = "Barbadian"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Belarus",
                            Nationality = "Belarusian"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Belgium",
                            Nationality = "Belgian"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Belize",
                            Nationality = "Belizean"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Benin",
                            Nationality = "Beninese"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Bermuda",
                            Nationality = "Bermudian"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Bhutan",
                            Nationality = "Bhutanese"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Bolivia",
                            Nationality = "Bolivian"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Bosnia and Herzegovina",
                            Nationality = "Bosnian, Herzegovinian"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Botswana",
                            Nationality = "Motswana"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Bouvet Island",
                            Nationality = "?"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Brazil",
                            Nationality = "Brazilian"
                        },
                        new
                        {
                            Id = 31,
                            Name = "British Antarctic Territory",
                            Nationality = "Dutch"
                        },
                        new
                        {
                            Id = 32,
                            Name = "British Indian Ocean Territory",
                            Nationality = "Indian"
                        },
                        new
                        {
                            Id = 33,
                            Name = "British Virgin Islands",
                            Nationality = "Virgin Islander"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Brunei",
                            Nationality = "Bruneian"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Bulgaria",
                            Nationality = "Bulgarian"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Burkina Faso",
                            Nationality = "Burkinabe"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Burundi",
                            Nationality = "Burundian"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Cambodia",
                            Nationality = "Cambodian"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Cameroon",
                            Nationality = "Cameroonian"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Canada",
                            Nationality = "Canadian"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Canton and Enderbury Islands",
                            Nationality = "?"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Cape Verde",
                            Nationality = "Cape Verdian"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Cayman Islands",
                            Nationality = "Caymanian"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Central African Republic",
                            Nationality = "Central African"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Chad",
                            Nationality = "Chadian"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Chile",
                            Nationality = "Chilean"
                        },
                        new
                        {
                            Id = 47,
                            Name = "China",
                            Nationality = "Chinese"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Christmas Island",
                            Nationality = "Christmas Island"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Cocos [Keeling] Islands",
                            Nationality = "Cocos Islander"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Colombia",
                            Nationality = "Colombian"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Comoros",
                            Nationality = "Comoran"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Congo - Brazzaville",
                            Nationality = "Congolese"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Congo - Kinshasa",
                            Nationality = "Congolese"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Cook Islands",
                            Nationality = "Cook Islander"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Costa Rica",
                            Nationality = "Costa Rican"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Croatia",
                            Nationality = "Croatian"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Cuba",
                            Nationality = "Cuban"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Cyprus",
                            Nationality = "Cypriot"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Czech Republic",
                            Nationality = "Czech"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Côte d’Ivoire",
                            Nationality = "Ivorian"
                        },
                        new
                        {
                            Id = 61,
                            Name = "Denmark",
                            Nationality = "Danish"
                        },
                        new
                        {
                            Id = 62,
                            Name = "Djibouti",
                            Nationality = "Djibouti"
                        },
                        new
                        {
                            Id = 63,
                            Name = "Dominica",
                            Nationality = "Dominican"
                        },
                        new
                        {
                            Id = 64,
                            Name = "Dominican Republic",
                            Nationality = "Dominican"
                        },
                        new
                        {
                            Id = 65,
                            Name = "Dronning Maud Land",
                            Nationality = "?"
                        },
                        new
                        {
                            Id = 66,
                            Name = "Ecuador",
                            Nationality = "Ecuadorean"
                        },
                        new
                        {
                            Id = 67,
                            Name = "Egypt",
                            Nationality = "Egyptian"
                        },
                        new
                        {
                            Id = 68,
                            Name = "El Salvador",
                            Nationality = "Salvadoran"
                        },
                        new
                        {
                            Id = 69,
                            Name = "Equatorial Guinea",
                            Nationality = "Equatorial Guinean"
                        },
                        new
                        {
                            Id = 70,
                            Name = "Eritrea",
                            Nationality = "Eritrean"
                        },
                        new
                        {
                            Id = 71,
                            Name = "Estonia",
                            Nationality = "Estonian"
                        },
                        new
                        {
                            Id = 72,
                            Name = "Ethiopia",
                            Nationality = "Ethiopian"
                        },
                        new
                        {
                            Id = 73,
                            Name = "Falkland Islands",
                            Nationality = "Falkland Islander"
                        },
                        new
                        {
                            Id = 74,
                            Name = "Faroe Islands",
                            Nationality = "Faroese"
                        },
                        new
                        {
                            Id = 75,
                            Name = "Fiji",
                            Nationality = "Fijian"
                        },
                        new
                        {
                            Id = 76,
                            Name = "Finland",
                            Nationality = "Finnish"
                        },
                        new
                        {
                            Id = 77,
                            Name = "France",
                            Nationality = "French"
                        },
                        new
                        {
                            Id = 78,
                            Name = "French Guiana",
                            Nationality = "?"
                        },
                        new
                        {
                            Id = 79,
                            Name = "French Polynesia",
                            Nationality = "French Polynesian"
                        },
                        new
                        {
                            Id = 80,
                            Name = "French Southern Territories",
                            Nationality = "French"
                        },
                        new
                        {
                            Id = 81,
                            Name = "French Southern and Antarctic Territories",
                            Nationality = "?"
                        },
                        new
                        {
                            Id = 82,
                            Name = "Gabon",
                            Nationality = "Gabonese"
                        },
                        new
                        {
                            Id = 83,
                            Name = "Gambia",
                            Nationality = "Gambian"
                        },
                        new
                        {
                            Id = 84,
                            Name = "Georgia",
                            Nationality = "Georgian"
                        },
                        new
                        {
                            Id = 85,
                            Name = "Germany",
                            Nationality = "German"
                        },
                        new
                        {
                            Id = 86,
                            Name = "Ghana",
                            Nationality = "Ghanaian"
                        },
                        new
                        {
                            Id = 87,
                            Name = "Gibraltar",
                            Nationality = "Gibraltar"
                        },
                        new
                        {
                            Id = 88,
                            Name = "Greece",
                            Nationality = "Greek"
                        },
                        new
                        {
                            Id = 89,
                            Name = "Greenland",
                            Nationality = "Greenlandic"
                        },
                        new
                        {
                            Id = 90,
                            Name = "Grenada",
                            Nationality = "Grenadian"
                        },
                        new
                        {
                            Id = 91,
                            Name = "Guadeloupe",
                            Nationality = "Guadeloupian"
                        },
                        new
                        {
                            Id = 92,
                            Name = "Guam",
                            Nationality = "Guamanian"
                        },
                        new
                        {
                            Id = 93,
                            Name = "Guatemala",
                            Nationality = "Guatemalan"
                        },
                        new
                        {
                            Id = 94,
                            Name = "Guernsey",
                            Nationality = "Channel Islander"
                        },
                        new
                        {
                            Id = 95,
                            Name = "Guinea",
                            Nationality = "Guinean"
                        },
                        new
                        {
                            Id = 96,
                            Name = "Guinea-Bissau",
                            Nationality = "Guinea-Bissauan"
                        },
                        new
                        {
                            Id = 97,
                            Name = "Guyana",
                            Nationality = "Guyanese"
                        },
                        new
                        {
                            Id = 98,
                            Name = "Haiti",
                            Nationality = "Haitian"
                        },
                        new
                        {
                            Id = 99,
                            Name = "Heard Island and McDonald Islands",
                            Nationality = "Heard and McDonald Islander"
                        },
                        new
                        {
                            Id = 100,
                            Name = "Honduras",
                            Nationality = "Honduran"
                        },
                        new
                        {
                            Id = 101,
                            Name = "Hong Kong SAR China",
                            Nationality = "Chinese"
                        },
                        new
                        {
                            Id = 102,
                            Name = "Hungary",
                            Nationality = "Hungarian"
                        },
                        new
                        {
                            Id = 103,
                            Name = "Iceland",
                            Nationality = "Icelander"
                        },
                        new
                        {
                            Id = 104,
                            Name = "India",
                            Nationality = "Indian"
                        },
                        new
                        {
                            Id = 105,
                            Name = "Indonesia",
                            Nationality = "Indonesian"
                        },
                        new
                        {
                            Id = 106,
                            Name = "Iran",
                            Nationality = "Iranian"
                        },
                        new
                        {
                            Id = 107,
                            Name = "Iraq",
                            Nationality = "Iraqi"
                        },
                        new
                        {
                            Id = 108,
                            Name = "Ireland",
                            Nationality = "Irish"
                        },
                        new
                        {
                            Id = 109,
                            Name = "Isle of Man",
                            Nationality = "Manx"
                        },
                        new
                        {
                            Id = 110,
                            Name = "Israel",
                            Nationality = "Israeli"
                        },
                        new
                        {
                            Id = 111,
                            Name = "Italy",
                            Nationality = "Italian"
                        },
                        new
                        {
                            Id = 112,
                            Name = "Jamaica",
                            Nationality = "Jamaican"
                        },
                        new
                        {
                            Id = 113,
                            Name = "Japan",
                            Nationality = "Japanese"
                        },
                        new
                        {
                            Id = 114,
                            Name = "Jersey",
                            Nationality = "Channel Islander"
                        },
                        new
                        {
                            Id = 115,
                            Name = "Johnston Island",
                            Nationality = "?"
                        },
                        new
                        {
                            Id = 116,
                            Name = "Jordan",
                            Nationality = "Jordanian"
                        },
                        new
                        {
                            Id = 117,
                            Name = "Kazakhstan",
                            Nationality = "Kazakhstani"
                        },
                        new
                        {
                            Id = 118,
                            Name = "Kenya",
                            Nationality = "Kenyan"
                        },
                        new
                        {
                            Id = 119,
                            Name = "Kiribati",
                            Nationality = "I-Kiribati"
                        },
                        new
                        {
                            Id = 120,
                            Name = "Kuwait",
                            Nationality = "Kuwaiti"
                        },
                        new
                        {
                            Id = 121,
                            Name = "Kyrgyzstan",
                            Nationality = "Kirghiz"
                        },
                        new
                        {
                            Id = 122,
                            Name = "Laos",
                            Nationality = "Laotian"
                        },
                        new
                        {
                            Id = 123,
                            Name = "Latvia",
                            Nationality = "Latvian"
                        },
                        new
                        {
                            Id = 124,
                            Name = "Lebanon",
                            Nationality = "Lebanese"
                        },
                        new
                        {
                            Id = 125,
                            Name = "Lesotho",
                            Nationality = "Mosotho"
                        },
                        new
                        {
                            Id = 126,
                            Name = "Liberia",
                            Nationality = "Liberian"
                        },
                        new
                        {
                            Id = 127,
                            Name = "Libya",
                            Nationality = "Libyan"
                        },
                        new
                        {
                            Id = 128,
                            Name = "Liechtenstein",
                            Nationality = "Liechtensteiner"
                        },
                        new
                        {
                            Id = 129,
                            Name = "Lithuania",
                            Nationality = "Lithuanian"
                        },
                        new
                        {
                            Id = 130,
                            Name = "Luxembourg",
                            Nationality = "Luxembourger"
                        },
                        new
                        {
                            Id = 131,
                            Name = "Macau SAR China",
                            Nationality = "Chinese"
                        },
                        new
                        {
                            Id = 132,
                            Name = "Macedonia",
                            Nationality = "Macedonian"
                        },
                        new
                        {
                            Id = 133,
                            Name = "Madagascar",
                            Nationality = "Malagasy"
                        },
                        new
                        {
                            Id = 134,
                            Name = "Malawi",
                            Nationality = "Malawian"
                        },
                        new
                        {
                            Id = 135,
                            Name = "Malaysia",
                            Nationality = "Malaysian"
                        },
                        new
                        {
                            Id = 136,
                            Name = "Maldives",
                            Nationality = "Maldivan"
                        },
                        new
                        {
                            Id = 137,
                            Name = "Mali",
                            Nationality = "Malian"
                        },
                        new
                        {
                            Id = 138,
                            Name = "Malta",
                            Nationality = "Maltese"
                        },
                        new
                        {
                            Id = 139,
                            Name = "Marshall Islands",
                            Nationality = "Marshallese"
                        },
                        new
                        {
                            Id = 140,
                            Name = "Martinique",
                            Nationality = "French"
                        },
                        new
                        {
                            Id = 141,
                            Name = "Mauritania",
                            Nationality = "Mauritanian"
                        },
                        new
                        {
                            Id = 142,
                            Name = "Mauritius",
                            Nationality = "Mauritian"
                        },
                        new
                        {
                            Id = 143,
                            Name = "Mayotte",
                            Nationality = "French"
                        },
                        new
                        {
                            Id = 144,
                            Name = "Metropolitan France",
                            Nationality = "?"
                        },
                        new
                        {
                            Id = 145,
                            Name = "Mexico",
                            Nationality = "Mexican"
                        },
                        new
                        {
                            Id = 146,
                            Name = "Micronesia",
                            Nationality = "Micronesian"
                        },
                        new
                        {
                            Id = 147,
                            Name = "Midway Islands"
                        },
                        new
                        {
                            Id = 148,
                            Name = "Moldova",
                            Nationality = "Moldovan"
                        },
                        new
                        {
                            Id = 149,
                            Name = "Monaco",
                            Nationality = "Monegasque"
                        },
                        new
                        {
                            Id = 150,
                            Name = "Mongolia",
                            Nationality = "Mongolian"
                        },
                        new
                        {
                            Id = 151,
                            Name = "Montenegro",
                            Nationality = "Montenegrin"
                        },
                        new
                        {
                            Id = 152,
                            Name = "Montserrat",
                            Nationality = "Montserratian"
                        },
                        new
                        {
                            Id = 153,
                            Name = "Morocco",
                            Nationality = "Moroccan"
                        },
                        new
                        {
                            Id = 154,
                            Name = "Mozambique",
                            Nationality = "Mozambican"
                        },
                        new
                        {
                            Id = 155,
                            Name = "Myanmar [Burma]",
                            Nationality = "Myanmar"
                        },
                        new
                        {
                            Id = 156,
                            Name = "Namibia",
                            Nationality = "Namibian"
                        },
                        new
                        {
                            Id = 157,
                            Name = "Nauru",
                            Nationality = "Nauruan"
                        },
                        new
                        {
                            Id = 158,
                            Name = "Nepal",
                            Nationality = "Nepalese"
                        },
                        new
                        {
                            Id = 159,
                            Name = "Netherlands Antilles",
                            Nationality = "Dutch"
                        },
                        new
                        {
                            Id = 160,
                            Name = "Netherlands",
                            Nationality = "Dutch"
                        },
                        new
                        {
                            Id = 161,
                            Name = "Neutral Zone",
                            Nationality = "?"
                        },
                        new
                        {
                            Id = 162,
                            Name = "New Caledonia",
                            Nationality = "New Caledonian"
                        },
                        new
                        {
                            Id = 163,
                            Name = "New Zealand",
                            Nationality = "New Zealander"
                        },
                        new
                        {
                            Id = 164,
                            Name = "Nicaragua",
                            Nationality = "Nicaraguan"
                        },
                        new
                        {
                            Id = 165,
                            Name = "Niger",
                            Nationality = "Nigerian"
                        },
                        new
                        {
                            Id = 166,
                            Name = "Nigeria",
                            Nationality = "Nigerian"
                        },
                        new
                        {
                            Id = 167,
                            Name = "Niue",
                            Nationality = "Niuean"
                        },
                        new
                        {
                            Id = 168,
                            Name = "Norfolk Island",
                            Nationality = "Norfolk Islander"
                        },
                        new
                        {
                            Id = 169,
                            Name = "North Korea",
                            Nationality = "North Korean"
                        },
                        new
                        {
                            Id = 170,
                            Name = "North Vietnam",
                            Nationality = "?"
                        },
                        new
                        {
                            Id = 171,
                            Name = "Northern Mariana Islands",
                            Nationality = "American"
                        },
                        new
                        {
                            Id = 172,
                            Name = "Norway",
                            Nationality = "Norwegian"
                        },
                        new
                        {
                            Id = 173,
                            Name = "Oman",
                            Nationality = "Omani"
                        },
                        new
                        {
                            Id = 174,
                            Name = "Pacific Islands Trust Territory",
                            Nationality = "?"
                        },
                        new
                        {
                            Id = 175,
                            Name = "Pakistan",
                            Nationality = "Pakistani"
                        },
                        new
                        {
                            Id = 176,
                            Name = "Palau",
                            Nationality = "Palauan"
                        },
                        new
                        {
                            Id = 177,
                            Name = "Palestinian Territories",
                            Nationality = "Palestinian"
                        },
                        new
                        {
                            Id = 178,
                            Name = "Panama Canal Zone",
                            Nationality = "?"
                        },
                        new
                        {
                            Id = 179,
                            Name = "Panama",
                            Nationality = "Panamanian"
                        },
                        new
                        {
                            Id = 180,
                            Name = "Papua New Guinea",
                            Nationality = "Papua New Guinean"
                        },
                        new
                        {
                            Id = 181,
                            Name = "Paraguay",
                            Nationality = "Paraguayan"
                        },
                        new
                        {
                            Id = 182,
                            Name = "Peru",
                            Nationality = "Peruvian"
                        },
                        new
                        {
                            Id = 183,
                            Name = "Philippines",
                            Nationality = "Filipino"
                        },
                        new
                        {
                            Id = 184,
                            Name = "Pitcairn Islands",
                            Nationality = "Pitcairn Islander"
                        },
                        new
                        {
                            Id = 185,
                            Name = "Poland",
                            Nationality = "Polish"
                        },
                        new
                        {
                            Id = 186,
                            Name = "Portugal",
                            Nationality = "Portuguese"
                        },
                        new
                        {
                            Id = 187,
                            Name = "Puerto Rico",
                            Nationality = "Puerto Rican"
                        },
                        new
                        {
                            Id = 188,
                            Name = "Qatar",
                            Nationality = "Qatari"
                        },
                        new
                        {
                            Id = 189,
                            Name = "Romania",
                            Nationality = "Romanian"
                        },
                        new
                        {
                            Id = 190,
                            Name = "Russia",
                            Nationality = "Russian"
                        },
                        new
                        {
                            Id = 191,
                            Name = "Rwanda",
                            Nationality = "Rwandan"
                        },
                        new
                        {
                            Id = 192,
                            Name = "Réunion",
                            Nationality = "French"
                        },
                        new
                        {
                            Id = 193,
                            Name = "Saint Barthélemy",
                            Nationality = "Saint Barthélemy Islander"
                        },
                        new
                        {
                            Id = 194,
                            Name = "Saint Helena",
                            Nationality = "Saint Helenian"
                        },
                        new
                        {
                            Id = 195,
                            Name = "Saint Kitts and Nevis",
                            Nationality = "Kittian and Nevisian"
                        },
                        new
                        {
                            Id = 196,
                            Name = "Saint Lucia",
                            Nationality = "Saint Lucian"
                        },
                        new
                        {
                            Id = 197,
                            Name = "Saint Martin",
                            Nationality = "Saint Martin Islander"
                        },
                        new
                        {
                            Id = 198,
                            Name = "Saint Pierre and Miquelon",
                            Nationality = "French"
                        },
                        new
                        {
                            Id = 199,
                            Name = "Saint Vincent and the Grenadines",
                            Nationality = "Saint Vincentian"
                        },
                        new
                        {
                            Id = 200,
                            Name = "Samoa",
                            Nationality = "Samoan"
                        },
                        new
                        {
                            Id = 201,
                            Name = "San Marino",
                            Nationality = "Sammarinese"
                        },
                        new
                        {
                            Id = 202,
                            Name = "Saudi Arabia",
                            Nationality = "Saudi Arabian"
                        },
                        new
                        {
                            Id = 203,
                            Name = "Senegal",
                            Nationality = "Senegalese"
                        },
                        new
                        {
                            Id = 204,
                            Name = "Serbia and Montenegro",
                            Nationality = "Montenegrins, Serbs"
                        },
                        new
                        {
                            Id = 205,
                            Name = "Serbia",
                            Nationality = "Serbian"
                        },
                        new
                        {
                            Id = 206,
                            Name = "Seychelles",
                            Nationality = "Seychellois"
                        },
                        new
                        {
                            Id = 207,
                            Name = "Sierra Leone",
                            Nationality = "Sierra Leonean"
                        },
                        new
                        {
                            Id = 208,
                            Name = "Singapore",
                            Nationality = "Singaporean"
                        },
                        new
                        {
                            Id = 209,
                            Name = "Slovakia",
                            Nationality = "Slovak"
                        },
                        new
                        {
                            Id = 210,
                            Name = "Slovenia",
                            Nationality = "Slovene"
                        },
                        new
                        {
                            Id = 211,
                            Name = "Solomon Islands",
                            Nationality = "Solomon Islander"
                        },
                        new
                        {
                            Id = 212,
                            Name = "Somalia",
                            Nationality = "Somali"
                        },
                        new
                        {
                            Id = 213,
                            Name = "South Africa",
                            Nationality = "South African"
                        },
                        new
                        {
                            Id = 214,
                            Name = "South Georgia and the South Sandwich Islands",
                            Nationality = "South Georgia and the South Sandwich Islander"
                        },
                        new
                        {
                            Id = 215,
                            Name = "South Korea",
                            Nationality = "South Korean"
                        },
                        new
                        {
                            Id = 216,
                            Name = "Spain",
                            Nationality = "Spanish"
                        },
                        new
                        {
                            Id = 217,
                            Name = "Sri Lanka",
                            Nationality = "Sri Lankan"
                        },
                        new
                        {
                            Id = 218,
                            Name = "Sudan",
                            Nationality = "Sudanese"
                        },
                        new
                        {
                            Id = 219,
                            Name = "Suriname",
                            Nationality = "Surinamer"
                        },
                        new
                        {
                            Id = 220,
                            Name = "Svalbard and Jan Mayen",
                            Nationality = "Norwegian"
                        },
                        new
                        {
                            Id = 221,
                            Name = "Swaziland",
                            Nationality = "Swazi"
                        },
                        new
                        {
                            Id = 222,
                            Name = "Sweden",
                            Nationality = "Swedish"
                        },
                        new
                        {
                            Id = 223,
                            Name = "Switzerland",
                            Nationality = "Swiss"
                        },
                        new
                        {
                            Id = 224,
                            Name = "Syria",
                            Nationality = "Syrian"
                        },
                        new
                        {
                            Id = 225,
                            Name = "São Tomé and Príncipe",
                            Nationality = "Sao Tomean"
                        },
                        new
                        {
                            Id = 226,
                            Name = "Taiwan",
                            Nationality = "Taiwanese"
                        },
                        new
                        {
                            Id = 227,
                            Name = "Tajikistan",
                            Nationality = "Tadzhik"
                        },
                        new
                        {
                            Id = 228,
                            Name = "Tanzania",
                            Nationality = "Tanzanian"
                        },
                        new
                        {
                            Id = 229,
                            Name = "Thailand",
                            Nationality = "Thai"
                        },
                        new
                        {
                            Id = 230,
                            Name = "Timor-Leste",
                            Nationality = "East Timorese"
                        },
                        new
                        {
                            Id = 231,
                            Name = "Togo",
                            Nationality = "Togolese"
                        },
                        new
                        {
                            Id = 232,
                            Name = "Tokelau",
                            Nationality = "Tokelauan"
                        },
                        new
                        {
                            Id = 233,
                            Name = "Tonga",
                            Nationality = "Tongan"
                        },
                        new
                        {
                            Id = 234,
                            Name = "Trinidad and Tobago",
                            Nationality = "Trinidadian"
                        },
                        new
                        {
                            Id = 235,
                            Name = "Tunisia",
                            Nationality = "Tunisian"
                        },
                        new
                        {
                            Id = 236,
                            Name = "Turkey",
                            Nationality = "Turkish"
                        },
                        new
                        {
                            Id = 237,
                            Name = "Turkmenistan",
                            Nationality = "Turkmen"
                        },
                        new
                        {
                            Id = 238,
                            Name = "Turks and Caicos Islands",
                            Nationality = "Turks and Caicos Islander"
                        },
                        new
                        {
                            Id = 239,
                            Name = "Tuvalu",
                            Nationality = "Tuvaluan"
                        },
                        new
                        {
                            Id = 240,
                            Name = "U.S. Minor Outlying Islands",
                            Nationality = "American"
                        },
                        new
                        {
                            Id = 241,
                            Name = "U.S. Miscellaneous Pacific Islands",
                            Nationality = "?"
                        },
                        new
                        {
                            Id = 242,
                            Name = "U.S. Virgin Islands",
                            Nationality = "Virgin Islander"
                        },
                        new
                        {
                            Id = 243,
                            Name = "Uganda",
                            Nationality = "Ugandan"
                        },
                        new
                        {
                            Id = 244,
                            Name = "Ukraine",
                            Nationality = "Ukrainian"
                        },
                        new
                        {
                            Id = 245,
                            Name = "Union of Soviet Socialist Republics",
                            Nationality = "?"
                        },
                        new
                        {
                            Id = 246,
                            Name = "United Arab Emirates",
                            Nationality = "Emirati"
                        },
                        new
                        {
                            Id = 247,
                            Name = "United Kingdom",
                            Nationality = "British"
                        },
                        new
                        {
                            Id = 248,
                            Name = "United States",
                            Nationality = "American"
                        },
                        new
                        {
                            Id = 249,
                            Name = "Uruguay",
                            Nationality = "Uruguayan"
                        },
                        new
                        {
                            Id = 250,
                            Name = "Uzbekistan",
                            Nationality = "Uzbekistani"
                        },
                        new
                        {
                            Id = 251,
                            Name = "Vanuatu",
                            Nationality = "Ni-Vanuatu"
                        },
                        new
                        {
                            Id = 252,
                            Name = "Vatican City",
                            Nationality = "Italian"
                        },
                        new
                        {
                            Id = 253,
                            Name = "Venezuela",
                            Nationality = "Venezuelan"
                        },
                        new
                        {
                            Id = 254,
                            Name = "Vietnam",
                            Nationality = "Vietnamese"
                        },
                        new
                        {
                            Id = 255,
                            Name = "Wake Island",
                            Nationality = "?"
                        },
                        new
                        {
                            Id = 256,
                            Name = "Wallis and Futuna",
                            Nationality = "Wallis and Futuna Islander"
                        },
                        new
                        {
                            Id = 257,
                            Name = "Western Sahara",
                            Nationality = "Sahrawi"
                        },
                        new
                        {
                            Id = 258,
                            Name = "Yemen",
                            Nationality = "Yemeni"
                        },
                        new
                        {
                            Id = 259,
                            Name = "Zambia",
                            Nationality = "Zambian"
                        },
                        new
                        {
                            Id = 260,
                            Name = "Zimbabwe",
                            Nationality = "Zimbabwean"
                        },
                        new
                        {
                            Id = 261,
                            Name = "Åland Islands",
                            Nationality = "Swedish"
                        });
                });

            modelBuilder.Entity("dadachMovie.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40) CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("dadachMovie.Entities.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ImdbId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<bool>("InTheaters")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Picture")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<float>("Rate")
                        .HasColumnType("float");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300) CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("ImdbId")
                        .IsUnique();

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("dadachMovie.Entities.MoviesCasts", b =>
                {
                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("Character")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("MovieId", "PersonId");

                    b.HasIndex("PersonId");

                    b.ToTable("MoviesCasts");
                });

            modelBuilder.Entity("dadachMovie.Entities.MoviesCountries", b =>
                {
                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.HasKey("MovieId", "CountryId");

                    b.HasIndex("CountryId");

                    b.ToTable("MoviesCountries");
                });

            modelBuilder.Entity("dadachMovie.Entities.MoviesDirectors", b =>
                {
                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("MovieId", "PersonId");

                    b.HasIndex("PersonId");

                    b.ToTable("MoviesDirectors");
                });

            modelBuilder.Entity("dadachMovie.Entities.MoviesGenres", b =>
                {
                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.HasKey("GenreId", "MovieId");

                    b.HasIndex("MovieId");

                    b.ToTable("MoviesGenres");
                });

            modelBuilder.Entity("dadachMovie.Entities.PeopleCountries", b =>
                {
                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.HasKey("PersonId", "CountryId");

                    b.HasIndex("CountryId");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("PeopleCountries");
                });

            modelBuilder.Entity("dadachMovie.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Biography")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<bool>("IsCast")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDirector")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120) CHARACTER SET utf8mb4");

                    b.Property<string>("Picture")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ShortBio")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("People");
                });

            modelBuilder.Entity("dadachMovie.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Picture")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTimeOffset>("RegisterDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("dadachMovie.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("dadachMovie.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dadachMovie.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("dadachMovie.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("dadachMovie.Entities.MoviesCasts", b =>
                {
                    b.HasOne("dadachMovie.Entities.Movie", "Movie")
                        .WithMany("Casts")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dadachMovie.Entities.Person", "Person")
                        .WithMany("Casts")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("dadachMovie.Entities.MoviesCountries", b =>
                {
                    b.HasOne("dadachMovie.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dadachMovie.Entities.Movie", "Movie")
                        .WithMany("Countries")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("dadachMovie.Entities.MoviesDirectors", b =>
                {
                    b.HasOne("dadachMovie.Entities.Movie", "Movie")
                        .WithMany("Directors")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dadachMovie.Entities.Person", "Person")
                        .WithMany("Directors")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("dadachMovie.Entities.MoviesGenres", b =>
                {
                    b.HasOne("dadachMovie.Entities.Genre", "Genre")
                        .WithMany("Genres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dadachMovie.Entities.Movie", "Movie")
                        .WithMany("Genres")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("dadachMovie.Entities.PeopleCountries", b =>
                {
                    b.HasOne("dadachMovie.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dadachMovie.Entities.Person", "Person")
                        .WithOne("Countries")
                        .HasForeignKey("dadachMovie.Entities.PeopleCountries", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("dadachMovie.Entities.User", b =>
                {
                    b.HasOne("dadachMovie.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("dadachMovie.Entities.Genre", b =>
                {
                    b.Navigation("Genres");
                });

            modelBuilder.Entity("dadachMovie.Entities.Movie", b =>
                {
                    b.Navigation("Casts");

                    b.Navigation("Countries");

                    b.Navigation("Directors");

                    b.Navigation("Genres");
                });

            modelBuilder.Entity("dadachMovie.Entities.Person", b =>
                {
                    b.Navigation("Casts");

                    b.Navigation("Countries");

                    b.Navigation("Directors");
                });
#pragma warning restore 612, 618
        }
    }
}
